name: 05 - Modificaci칩n del c칩digo
on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Compilar (validaci칩n r치pida)
        run: |
          python -m compileall .
          echo "codigo compila correctamente"
          echo "Notificar a: DevA, DevB, IT1, IT2"
