name: 02 - Modificaci贸n de cliente existente
on:
  push:
    paths:
      - "data/clients/**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar a equipo
        run: |
          echo "Modificaci贸n de cliente detectada"
          echo "Notificar a: DevA, DevB, IT1, IT2, Atenci贸n1, Atenci贸n2"
